main: xyz.versedev.practice.Shadow
name: Shadow
version: '${project.version}-${git.commit.id.abbrev}' # ${git.commit.id.abbrev}
author: Zatrex, Trakser, Funky, Discord, Marc, Mojang, md5, SpigotMC, PaperMC
depend:
  - WorldEdit
softdepend:
  - PlaceholderAPI
  - VerseCore
  - Volcano
  - Apollo-Bukkit
  - AquaCore
  - PolarCord
  - Phoenix
  - PhoenixAC
  - KarhuLoader
  - PolarLoader
  - Replays
  - Citizens
