# This configuration file is part of a Verse Development Project. Purchased at https://dsc.gg/versedev
LICENSE: "YOUR_LICENSE" # Add your license key here (removed currently)
GENERAL: 
  # This is where players will teleport on join and after a match
  SPAWN-LOCATION: "world:0.0:70.0:0.0:0.45256472:-0.7543715"
  # What theme we should give to the new players?
  DEFAULT-THEME: "AQUA"
MATCH:
  # Should we clear placed blocks after each round of Bridges?
  CLEAR-BLOCKS: false
  # Remove empty potion bottles
  REMOVE_POTION_BOTTLE: false
  # Should we show the player respawn title?
  RESPAWN-TITLE: true
  # Should we broadcast player respawn message?
  BROADCAST-RESPAWN: true
  # Should we enable bow boost in match?
  BOW-BOOST:
    ENABLED: true
    MINIMIZE-DAMAGE: false
    KNOCKBACK-VELOCITY:
      X: 1.2
      Y: 1.0
      Z: 1.2
RANKED:
  # The minimum amount of won matches required by a player to join Ranked Queue
  # Set this to 0, if you don't want any limit
  REQUIRED-WINS: 10
  # Ranked Sumo rounds amount (TODO) Requested by mqaaz
  SUMO-ROUNDS: 1

# Will be used for bugs reports.
COMMIT-ID: "${git.commit.id.abbrev}"